language: python
sudo: required
python:
  - "3.5"
services:
  - mysql
env:
  - DJANGO_VERSION = 1.9.5, DB = mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
  - mv configs.test.json configs.json
install:
  - pip install -r requirements.txt

#before_script:
#  - python manage.py makemigrations
#  - python manage.py migrate
script: 
  - python manage.py test
  #true
