language: python
python:
  - "3.5"
services:
  - mysql
env:
  - DJANGO_VERSION = 1.9.5
#before_install:
  #Create mysql databases and tables
install:
  - pip install -r requirements.txt
script: 
  #- make test
  #- python manage.py test
  true
