language: python
sudo: required
python:
- '3.5'
services:
- mysql
env:
- DJANGO_VERSION = 1.9.5, DB = mysql
before_install:
- openssl aes-256-cbc -K $encrypted_16f15e662164_key -iv $encrypted_16f15e662164_iv
  -in id_rsa_deploy.enc -out ~\/.ssh/id_rsa_deploy -d
- openssl aes-256-cbc -K $encrypted_16f15e662164_key -iv $encrypted_16f15e662164_iv
  -in id_rsa_deploy.enc -out ~/.ssh/id_rsa_deploy -d
- chmod 600 ~/.ssh/id_rsa_deploy
- echo -e "Host 123.207.175.24\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
- mv configs.test.json configs.json
after_success:
- ssh ubuntu@123.207.175.24 -p $PASSWORD "./deploy.sh"
addons:
  ssh_known_hosts: 123.207.175.24
install:
- pip install -r requirements.txt
script:
- python manage.py test
