language: python
sudo: required
python:
- '3.5'
services:
- mysql
env:
- DJANGO_VERSION = 1.9.5, DB = mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
- mv configs.test.json configs.json
install:
- pip install -r requirements.txt
script:
- python manage.py test
dd:
- openssl aes-256-cbc -K $encrypted_d2dce55bfc52_key -iv $encrypted_d2dce55bfc52_iv
  -in configs.test.json.enc -out configs.test.json -d
