language: python
sudo: required
python:
- '3.5'
services:
- mysql
env:
- DJANGO_VERSION = 1.9.5, DB = mysql
before_deploy:
- sudo apt-get install sshpass  # 安装sshpass
before_install:
#- openssl aes-256-cbc -K $encrypted_16f15e662164_key -iv $encrypted_16f15e662164_iv
#  -in id_rsa.enc -out ~/.ssh/id_rsa -d
#- chmod 600 ~/.ssh/id_rsa
#- echo -e "Host 123.207.175.24\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
- mv configs.test.json configs.json
after_success:
- sudo sshpass -p $PASSWORD sudo ssh ubuntu@123.207.175.24 "cd WeChatTicket; git pull origin master"
addons:
  ssh_known_hosts: 123.207.175.24
install:
- pip install -r requirements.txt
script:
- python manage.py test
